# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Very Creative Blog Name
email: spejic88@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my personal blog, new posts every sometimes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://spejic88.github.io/" # the base hostname & protocol for your site
twitter_username: spejic88
github_username:  spejic88

# Build settings
markdown: kramdown
